DROP TABLE IF EXISTS "public"."transaction";
DROP TABLE IF EXISTS "public"."account";
DROP TABLE IF EXISTS "public"."client";

CREATE TABLE "public"."client" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 ),
	"address" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"age" int4,
	"code" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"full_name" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"gender" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"phone" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"client_id" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"password" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"status" bool,
	CONSTRAINT "client_pkey" PRIMARY KEY ( "id" ) 
);
CREATE TABLE "public"."account" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 ),
	"account_number" int4,
	"account_type" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"balance" NUMERIC ( 38, 2 ),
	"status" bool,
	"client_fk" int8 NOT NULL,
	CONSTRAINT "account_pkey" PRIMARY KEY ( "id" ),
	CONSTRAINT "fkhr6rysc8f4202s6mkcmd6lll1" FOREIGN KEY ( "client_fk" ) REFERENCES "public"."client" ( "id" ) ON DELETE NO ACTION ON UPDATE NO ACTION 
);
CREATE TABLE "public"."transaction" (
	"id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 ),
	"date_time" TIMESTAMP ( 6 ),
	"transaction_type" VARCHAR ( 255 ) COLLATE "pg_catalog"."default",
	"value" NUMERIC ( 38, 2 ),
	"account_fk" int8 NOT NULL,
	"old_balance" NUMERIC ( 38, 2 ),
	"new_balance" NUMERIC ( 38, 2 ),
	CONSTRAINT "transaction_pkey" PRIMARY KEY ( "id" ),
	CONSTRAINT "fkkncahr5w1epbu1hox3pbeb2up" FOREIGN KEY ( "account_fk" ) REFERENCES "public"."account" ( "id" ) ON DELETE NO ACTION ON UPDATE NO ACTION 
);